# Generated by Django 3.0.6 on 2020-05-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Target_Variable', models.CharField(max_length=100)),
                ('Date_Columne', models.CharField(max_length=100)),
                ('Email_Id', models.EmailField(max_length=254)),
            ],
        ),
    ]
