# Generated by Django 3.0.6 on 2020-05-09 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Input_Data',
        ),
    ]
